run:
  input:
    path: examples/sample_notes.csv
    type: csv
    text_columns: [Notes]
    csv_options:
      delimiter: ","
      encoding: "utf-8"
  output:
    path: null
    type: auto
    csv_options:
      delimiter: ","
      encoding: "utf-8"

options:
  redact_pronouns: false
  case_preserve_replacements: true
  placeholder_brackets: true

resources:
  # names_list_path: data/names.csv           # simple list: one column "name"
  names_structured_path: data/names.csv  # First/Middle/Last/Other Name i

rules:
  # Keep literal common words & time terms (prevents false positives)
  - type: word_guard
    keep_words: ["afternoon","week","weeks","weekend","time","year","years","hour","hours","minute","minutes","a","an","at","as","side","down"]

  # Protect key phrases and map directly
  - type: phrase_protect
    phrases:
      - text: "los angeles"
        replacement: LOCATION
      - text: "santa monica"
        replacement: LOCATION
      - text: "san francisco"
        replacement: LOCATION
      - text: "mercy medical"
        replacement: ORG
      - text: "michaels village"
        replacement: ORG
      - text: "the center"
        replacement: ORG
      - text: "wesley medical center"
        replacement: "ORG"
      - text: "NH"
        replacement: "PERSON"
      - text: "GU"
        replacement: "PERSON"
      - text: "Kendell Lorez"
        replacement: "PERSON"

  # Emails, phones, etc.
  - type: regex
    patterns:
      - pattern: "(?i)\\b[\\w.\\-]+@[\\w\\-]+\\.[\\w.\\-]+\\b"
        replacement: EMAIL
      - pattern: "(?i)\\b(?:\\+?1[\\s\\-\\.]*)?(?:\\(\\d{3}\\)|\\d{3})[\\s\\-\\.]?\\d{3}[\\s\\-\\.]?\\d{4}\\b"
        replacement: PHONE

  # Mixed alphanumeric IDs like D9C8DB1BC
  - type: id_alnum
    min_len: 6
    placeholder: CASEID

  # Structured names (full parity with your build_row_name_patterns)
  - type: structured_names
    csv_path: data/names.csv
    first_col: "First Name"
    middle_col: "Middle Name"
    last_col: "Last Name"
    other_prefix: "Other Name"
    skip_tokens: ["at","as","side"]
    placeholder: PERSON
    catch_first_middle_initial_no_last: true
    first_any_middle_initial_no_last: false         # set true only if you lack the middle in CSV and still want "First X." caught
    redact_standalone_middle_initial: true          # NEW: catches standalone "S" / "S."
  
  # Initials & acronyms policy (+ DPSS -> AGENCY mapping)
  - type: initials
    keep: ["YP","HCM","DOP","ADOP","DIM","LDIA","SBC","HWM","CSW","HCM/CSW","TCM","SHM","SHCO","SHC","TEM","TEC","EECM","MSWI","ED","ICCM","HWCM","COVID","COVID-19","COVID19","BBQ"]
    person: ["AS","K", "Seerat", "Jesenya"]
    org: ["HACLA","MFP","SUOS"]   # confirm SUOS; add/remove MV/HFSP/FSP as needed
    never: ["a","an","at","side","down"] #as
    special_map: {"DPSS": "AGENCY"}


  # Names from a simple list (optional but handy)
  - type: name_list
    placeholder: PERSON

  # Optional pronoun redaction toggle
  - type: pronoun
    pronouns: ["she","her","hers","he","him","his","they","them","theirs","ze","zir","xe","xem","xyr"]
    placeholder: PRONOUN

  # OPTIONAL: Presidio analyzer with forced orgs + filtering (off by default)
  - type: presidio_filtered
    enable: true
    forced_orgs: ["DPSS","MFP","The Center","Mercy Medical","Michaels Village"]
    date_exempt_terms: [
      "morning", "afternoon", "evening", "night", "midnight", "noon", "tonight",
      "today", "yesterday", "tomorrow", "day", "days", "daily",
      "week", "weeks", "weekend", "weekends",
      "month", "months", "monthly", "year", "years", "yearly",
      "hour", "hours", "minute", "minutes", "second", "seconds",
      "quarter", "semester", "trimester", "season", "seasons",
      "spring", "summer", "fall", "autumn", "winter",
      "January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December",
      "Mon", "Monday", "Tue", "Tues", "Tuesday", "Wed", "Wednesday",
      "Thu", "Thurs", "Thursday", "Fri", "Friday", "Sat", "Saturday", "Sun", "Sunday",
      "holiday", "holidays",
      "Christmas", "Easter", "Thanksgiving", "Halloween", "Hanukkah", "Kwanzaa", "New Year",
      "morningtime", "eveningtime", "lunchtime", "dinnertime", "bedtime",
      "today’s", "tomorrow’s", "yesterday’s", "this week"
    ]
    skip_words: ["at","side", "an", "weeks", "angeles", "YP", "BBQ"]
    placeholder_map:
      PERSON: PERSON
      LOCATION: LOCATION
      ORGANIZATION: ORG
      EMAIL_ADDRESS: EMAIL
      PHONE_NUMBER: PHONE
      CREDIT_CARD: CREDIT_CARD
      DATE: DATE
      DATE_TIME: DATE
      NUMBER: NUMBER
    special_map: {"DPSS": "AGENCY"}
