name: casenote-anon
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas>=2.2
      - pyyaml>=6.0
      - openpyxl>=3.1
      - presidio-analyzer>=2.2
      - presidio-anonymizer>=2.2
      - spacy>=3.7
      - tqdm>=4.66